const phrases = [
    "A proud subsidiary of Aperture Science.",
    "It works on my machine.",
    "The cake is a lie. So is our uptime.",
    "Please stand by for a system failure.",
    "Did you try turning it off and on again?",
    "In code we trust. All others pay cash.",
    "I see dead pixels.",
    "Documentation? Where we're going, we don't need documentation.",
    "We take security very seriously. Trust us.",
    "Now with 40% more bugs!",
    "Works 30% of the time, every time.",
    "SLA: Service Level Aspirational",
    "Black box testing: because we like surprises.",
    "Black Mesa can suck it.",
    "Our servers are powered by hamsters on wheels.",
    "99 little bugs in the code, 99 little bugs. Take one down, patch it around, 127 little bugs in the code.",
    "Pioneering the future of yesterday's technology.",
    "We taught JavaScript to segfault. It cried, we shipped.",
    "Quarterly goals: aggressive, charming, vaguely legal.",
    "Our uptime is directly proportional to your downtime.",
    "Security through obscurity. Mostly obscurity.",
    "We put the 'fun' in 'fundamental system failures'.",
    "The results of the security audit are in: 70% compliant, 100% mysterious.",
    "Our cloud is just someone else's computer.",
    "We don't do bugs, we do undocumented features.",
    "The model hallucinated a roadmap and it was inspirational.",
    "Nếu bạn có thể đọc điều này, bạn giải mã được thông điệp ẩn.",
    "We outsourced our QA to a Magic 8-Ball.",
    "We run on 100% recycled electrons.",
    
];